### ISSUE TITLE
UITextInput

### ISSUE THREAD

**Issue by vurf** [javalnanda/CharacterCounter#1]
Hi, what do you think about UITextInput? Without UITextField, UITextView and etc, and use only UITextInput?

**Comment by javalnanda** [comment]
Can you elaborate a bit more on it? UITextInput is enough if we just want to count the text. I have used the delegates of UITextField/UITextView to also restrict the text change beyond max limit.

**Comment by javalnanda** [comment]
Can you elaborate a bit more on it? UITextInput is enough if we just want to count the text. I have used the delegates of UITextField/UITextView to also restrict the text change beyond max limit.

**Comment by vurf** [comment]
May be use `UITextInputDelegate` and handle `func textDidChange(UITextInput?)` and try remove all code where have UITextField and UITextView and their delegates

**Comment by javalnanda** [comment]
`func textDidChange(UITextInput?)` is triggered after text changes. You cannot utilize it to restrict user from typing the text beyond the max limit. We need a delegate before the text change that is where respective delegates of textField and textView are used. I also want to monitor the end editing event to hide the component if it is not used as an accessory view. 
If this component was just to count the character length then definitely we can get rid of other code related to UITextField and UITextView. Feel free to open PR if you have a solution for the same by just using UITextInput and its delegate.
